[package]
  name = "server"
  version = "0.0.1"

  authors.workspace = true
  documentation.workspace = true
  edition.workspace = true
  homepage.workspace = true
  license.workspace = true
  readme.workspace = true
  repository.workspace = true

[lints]
  workspace = true

[dependencies]

  clap = { workspace = true }

  # Simple storage
  serde_json = { version = "1.0" }

  # Server
  axum = { version = "0.7.7" }
  axum-embed = { version = "0.1.0" }
  rust-embed = { version = "8.5.0", features = [] }
  serde = { version = "1.0", features = ["derive"] }
  tokio = { version = "1.41.1", features = ["rt-multi-thread"] }

  # Instrumentation
  tracing = { workspace = true }
  tracing-subscriber = { workspace = true }
